### ISSUE TITLE
frame not showing in correct position

### ISSUE THREAD

**Issue by alihanifi** [sag333ar/SRKControls#2]
hi,
i used the code just like in the readme file but the pop up is not positioned in the right place
images from simulator (6s)

<img width="376" alt="screen shot 1395-01-08 at 3 58 09 pm" src="https://cloud.githubusercontent.com/assets/18099249/14065180/3351f808-f435-11e5-8f43-159000cfe689.png">
<img width="377" alt="screen shot 1395-01-08 at 3 58 19 pm" src="https://cloud.githubusercontent.com/assets/18099249/14065181/34dec2dc-f435-11e5-98c6-59c2bbcbc9f4.png">

code for display is :
 ```
func comboBoxRectFromWhereToPresent(textField:SRKComboBox) -> CGRect {

        return textField.frame
    }

```

**Comment by sag333ar** [comment]
Hi if it is inside a view, you are suppose to calculate the frame size & then profile frame for pop-over.

**Comment by immnas** [comment]
How to have this on Navigation bar?
I am trying with 
    func comboBoxFromBarButton(textField:SRKComboBox) -> UIBarButtonItem? {
       return self.navigationItem.rightBarButtonItem
    }
but when I clicked at bar .. nothing happened?

**Comment by thang2410199** [comment]
Hello, I want to use SRKControls inside a tableview cell to create a Setting Page. What frame size should I give it ? Thank you.

**Comment by sag333ar** [comment]
You are suppose to calculate the frame size & then profile frame for pop-over.
Calculate the frame of the cell with `UITextfield` within the table-view. Refer to this [link](http://stackoverflow.com/questions/8082493/how-to-get-the-frame-of-a-view-inside-another-view). Return the same frame using following method
`comboBoxRectFromWhereToPresent`

**Comment by sag333ar** [comment]
I believe, your issue has been resolved. Closing ticket/issue.

**Comment by thang2410199** [comment]
thank you, I tried and it works well.
