### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [sag333ar/SRKControls#3]
Hey @sag333ar, your library is really interesting.

The only problem I found was the ```README.md```, which is a little bit confusing.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib.

What are your thoughts?

**Comment by sag333ar** [comment]
Hi @lfarah, That would be a great help. I would love to have your help in order to organize read-me file.

**Comment by sag333ar** [comment]
I have updated the read-me file. Please re-open the issue if read-me needs more improvement

**Comment by lfarah** [comment]
awesome 👍
