### ISSUE TITLE
how to add this pop on navigation bar?

### ISSUE THREAD

**Issue by immnas** [sag333ar/SRKControls#5]
How to have this on Navigation bar?
I am trying with 
func comboBoxFromBarButton(textField:SRKComboBox) -> UIBarButtonItem? {
return self.navigationItem.rightBarButtonItem
}
but when I clicked at bar .. nothing happened?

**Comment by sag333ar** [comment]
hi you are suppose to tap on textfield which will trigger all actions.

**Comment by immnas** [comment]
I have try many thing but its not woking on Navigation bar.

**Comment by sag333ar** [comment]
srk 333 iphone (without space add me on skype & explain your problem)
